<template><ul>
<li>原始类型
<ul>
<li>undefined</li>
<li>null</li>
<li>boolean</li>
<li>number</li>
<li>string</li>
<li>symbol
<ul>
<li>创建唯一标识</li>
<li>创建对象的“隐藏”属性</li>
</ul>
</li>
<li>bigInt</li>
</ul>
</li>
<li>引用类型
<ul>
<li>[对象](./JavaScript 对象.md)</li>
<li>内置对象</li>
</ul>
</li>
<li>函数
<ul>
<li><a href="https://github.com/mqyqingfeng/Blog/issues/10" target="_blank" rel="noopener noreferrer">形参之按值传递<OutboundLink/></a>
<ul>
<li>传参（实参到形参赋值的过程）
<ul>
<li>按值传递，即复制实参的值</li>
<li>引用传递，即复制实参的地址</li>
</ul>
</li>
<li>当变量为引用类型时，传参只是复制该变量的值（即引用的对象地址）</li>
</ul>
</li>
</ul>
</li>
</ul>
</template>