name: Build and Deloy

on:
  push:
    tags: 
      - page

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.DEPLOY_KEY }}
    - name: Install-node
      uses: actions/setup-node@v1
      with: 
        node-version: 10.x 
    - name: Install
      run: npm install
    - name: Build
      run: npm run docs:build
    - name: ADD CNAME
      run: echo "blog.laoergege.cn" > ./docs/CNAME
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: ./gh-pages
    - name: Copy Articles
      run: |
        rm -rf ./*
        mv ../laoergege-blog/docs/* ./
    - name: Deploy
      run: |
        git config --global user.email "13211239457@163.com"
        git config --global user.name "laoergege"
        git add .
        git commit -m 'publish'
        git push
