name: Build and Deloy

on:
  push:
    tags: 
      - page

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.DEPLOY_KEY }}
    - name: Install-node
      uses: actions/setup-node@v1
      with: 
        node-version: 10.x 
    - name: Install
      run: yarn
    - name: Build
      run: npm run docs:build
    - name: ADD CNAME
      run: cp CNAME docs/
