name: Build and Deloy

on:
  push:
    tags: 
      - page

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # 安装 node 环境
    - name: Install-node
      uses: actions/setup-node@v2
      with: 
        node-version: '14' 
    # 使用缓存，加速构建
    - name: Cache
      uses: actions/cache@v2
      with: 
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
    # 安装 pnpm
    - name: Install pnpm
      run: sudo npm install -g pnpm
    # 安装依赖
    - name: Install
      env: 
        CI: true
      run: pnpm install
    # 博客构建
    - name: Build
      run: npm run docs:build
    # 博客部署
    - run: mv ./dist ../dist
    - uses: actions/checkout@v2
      with:
        ref: 'deploy'
        fetch-depth: 0
    - run: |
        mv ../dist/* .
        git config --global user.email "826037047@qq.com"
        git config --global user.name "lys"
        git add .
        git commit -m 'publish'  
        git push
