name: Build and Deloy

on:
  push:
    tags: 
      - page

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN  }}
    - name: Install-node
      uses: actions/setup-node@v1
      with: 
        node-version: 10.x 
    - name: SetCache
      uses: actions/cache@v1
      with: 
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install
      env: 
        CI: true
      run: npm ci
    - name: Build
      run: npm run docs:build
    - name: Deploy
      run: |
        git config --global user.email "13211239457@163.com"
        git config --global user.name "laoergege"
        git checkout -b tmp
        git add .
        git commit -m 'publish'
        git pull origin master --rebase    
        git push origin tmp:master
