name: Build and Deloy

on:
  push:
    tags: 
      - page

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # 安装 node 环境
    - name: Install-node
      uses: actions/setup-node@v2
      with: 
        node-version: '14' 
    # 使用缓存，加速构建
    - name: Cache
      uses: actions/cache@v2
      with: 
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-
    # 安装 pnpm
    - name: Install pnpm
      run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6
      # 安装依赖
    - name: Install
      run: pnpm install
    # 博客构建
    - name: Build
      run: npm run docs:build
    # 博客部署
    - name: deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        repo: laoergege.github.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
