name: Publish Packages

on:
  push:
    # paths:
    #   - "packages/**"
    branches:
      - "master"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - run: tree
      - uses: ./.github/actions/install-runtime/action.yml
      - run: pnpm run package:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PKG_TOKEN: ${{ secrets.PKG_TOKEN }}
