name: Publish Packages

on:
  push:
    paths:
      - "packages/*"
    branches:
      - "master"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/install-runtime
      - run: pnpm run package:build
      - run: pnpm -r publish
        env:
          npm_config_scope: "@laoergege"
          npm_config__auth: ${{ secrets.NPM_TOKEN }}
      - run: pnpm publish
        env:
          npm_config_scope: "@laoergege"
          npm_config_register: https://npm.pkg.github.com/
          npm_config__auth: ${{ secrets.PKG_TOKEN }}
