name: Publish Packages

on:
  push:
    paths:
      - "packages/**"
    branches:
      - "master"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/install-runtime.yml
      - run: npm run package:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PKG_TOKEN: ${{ secrets.PKG_TOKEN }}
